### ISSUE TITLE
Is it possible to pass params to #block-slot for use in #yield-slot?

### ISSUE THREAD

**Issue by mnoble01** [ciena-blueplanet/ember-block-slots#49]
I'm trying to pass params to #block-slot like in this contrived example:

sample-component.hbs
```
{{#yield-slot 'slot' (block-params title)}}
  <div data-role={{role}}>
    {{yield}}
  </div>
{{/yield-slot}}
```
block-slots.hbs
```
{{#sample-component}}
  {{#block-slot 'slot' role='row' as |title|}}
    <h4>{{title}}</h4>
  {{/block-slot}}
{{/sample-component}}
```
And expecting:
```
<div data-role="row">
  <h4>My Title</h4
</div>
```

I know you can pass block-params from #yield-slot to #block-slot, but can it go the other way around?

**Comment by sglanzer-fire** [comment]
Hey @mnoble01 - no, the direction of block parameters is from the yield to the block.

Since the consumer controls the block and the yield is effectively just a placeholder what's the use case for passing parameters back to the yield?

I believe what you want in this case is a contextual component, there is an example here http://ciena-blueplanet.github.io/ember-block-slots/ in the purple section

```
  {{#yield-slot 'contextual' (block-params
    (hash role=(component 'role-component'))
    title
  )}}
    {{yield}}
  {{/yield-slot}}
```

```
  {{#block-slot 'contextual' as |componentHash title|}}
    {{#componentHash.role role='row'}}
      {{title}}
    {{/componentHash.role}}
  {{/block-slot}}
```

Hopefully that helps answer the question

**Comment by mnoble01** [comment]
Hi @sglanzer, that makes sense. I had a hunch that a contextual component was probably the way to go. 

Though it's not in the simple example I provided above, I was attempting to render a `data-key` attribute (unique id) per row. I ended up moving my iteration from the yield-slot to within the block-slot and using a contextual component as a wrapper, passing the `data-key` to that component.

Thanks for your help 👍
